"""Render application DTOs, ports and one-time skeletons from the YAML specification."""

import re
from pathlib import Path
from typing import NamedTuple

from tools.codegen.spec import ApplicationSpec, InterfaceSpec, MethodSpec, SpecError, UseCaseDefinition, import_object
from tools.codegen.types import SCALARS, SpecType, SpecTypeError, annotation, imports, parse_type

HEADER = "# Generated by tools.codegen from {source}. Do not edit."
SUFFIX = "UseCase"
_MEMBER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


class Skeleton(NamedTuple):
    """A skeleton to write or to append to what a human already wrote."""

    imports: str
    code: str


def imports_block(grouped: dict[str, set[str]]) -> str:
    return "\n".join(f"from {module} import {', '.join(sorted(names))}" for module, names in sorted(grouped.items()))


def docstring(text: str | None, indent: str) -> list[str]:
    """A docstring as source lines followed by a blank line; nothing for no text."""
    if not text:
        return []
    lines = text.strip().splitlines()
    if len(lines) == 1:
        return [f'{indent}"""{lines[0]}"""', ""]
    return [f'{indent}"""{lines[0]}', *(f"{indent}{line}".rstrip() for line in lines[1:]), f'{indent}"""', ""]


class ApplicationRenderer:
    """Renders DTOs, ports and skeletons from one application specification."""

    def __init__(self, package: str, path: Path, spec: ApplicationSpec, root: Path) -> None:
        self.package = package
        self.path = path
        self.spec = spec
        self.root = root
        self.module = path.stem
        self.imports: dict[str, set[str]] = {}

    def fail(self, message: str) -> SpecError:
        return SpecError(self.path, message)

    def add_import(self, module: str, name: str) -> None:
        self.imports.setdefault(module, set()).add(name)

    def parse(self, text: str, where: str) -> SpecType:
        try:
            spec_type = parse_type(text)
        except SpecTypeError as error:
            raise self.fail(f"{where}: {error}") from error
        if spec_type.default is not None:
            raise self.fail(f"{where}: a default value belongs to the API specification, not to a DTO")
        return spec_type

    def spec_type(self, text: str, where: str) -> SpecType:
        spec_type = self.parse(text, where)
        if not spec_type.is_scalar and spec_type.name not in (*self.spec.dtos, *self.spec.enums):
            known = ", ".join([*SCALARS, *self.spec.enums, *self.spec.dtos])
            raise self.fail(f"{where}: unknown type {text!r}, expected one of {known}")
        for module, symbol in imports(spec_type):
            self.add_import(module, symbol)
        return spec_type

    def input_name(self, use_case: str) -> str:
        if not use_case.endswith(SUFFIX):
            raise self.fail(f"{use_case}: a use case name must end with {SUFFIX}")
        return f"{use_case.removesuffix(SUFFIX)}Input"

    def dto_names(self) -> set[str]:
        return set(self.spec.dtos) | {self.input_name(use_case) for use_case in self.spec.use_cases}

    def has_dtos(self) -> bool:
        return bool(self.spec.enums or self.spec.dtos or self.spec.use_cases)

    def reference(self, text: str, where: str) -> str:
        """Resolve a type used outside the DTO module: a scalar, a DTO, enum or port of this file, a dotted path."""
        spec_type = self.parse(text, where)
        if spec_type.name == "none":
            if spec_type.many or spec_type.optional:
                raise self.fail(f"{where}: none has no list or optional form")
            return "None"
        if spec_type.is_scalar:
            for module, symbol in imports(spec_type):
                self.add_import(module, symbol)
            return annotation(spec_type)
        if "." in spec_type.name:
            value = import_object(self.path, f"{self.package}.{spec_type.name}")
            self.add_import(value.__module__, value.__name__)
            return annotation(SpecType(value.__name__, spec_type.many, spec_type.optional))
        if spec_type.name in self.spec.interfaces:
            self.add_import(f"{self.package}.application.interfaces.{self.module}", spec_type.name)
            return annotation(spec_type)
        if spec_type.name not in self.dto_names() | set(self.spec.enums):
            known = ", ".join([*SCALARS, *self.spec.enums, *sorted(self.dto_names()), *self.spec.interfaces])
            raise self.fail(f"{where}: unknown type {text!r}, expected one of {known} or a dotted path")
        self.add_import(f"{self.package}.application.dto.{self.module}", spec_type.name)
        return annotation(spec_type)

    def enum_code(self, name: str, values: list[str]) -> str:
        self.add_import("enum", "StrEnum")
        lines = [f"class {name}(StrEnum):"]
        for value in values:
            member = value.upper()
            if not _MEMBER.match(member):
                raise self.fail(f"{name}: {value!r} cannot be an enum member name")
            lines.append(f"    {member} = {value!r}")
        if not values:
            raise self.fail(f"{name}: an enum needs at least one value")
        return "\n".join(lines)

    def dto_code(self, name: str, fields: dict[str, str]) -> str:
        lines = ["@dto", f"class {name}:"]
        if not fields:
            lines.append("    pass")
        lines += [
            f"    {field}: {annotation(self.spec_type(text, f'{name}.{field}'))}" for field, text in fields.items()
        ]
        return "\n".join(lines)

    def check_output(self, use_case: str, definition: UseCaseDefinition) -> None:
        """A use case takes and returns DTOs: the dto-decorator check rejects anything else."""
        name = parse_type(definition.output).name
        if name != "none" and name not in self.dto_names():
            raise self.fail(f"{use_case}: output must be none or a DTO of this file, got {definition.output!r}")

    def render_dtos(self) -> str:
        self.imports = {}
        blocks = [self.enum_code(name, values) for name, values in self.spec.enums.items()]
        blocks += [self.dto_code(name, fields) for name, fields in self.spec.dtos.items()]
        for use_case, definition in self.spec.use_cases.items():
            self.check_output(use_case, definition)
            blocks.append(self.dto_code(self.input_name(use_case), definition.input))
        if self.spec.dtos or self.spec.use_cases:
            self.add_import(f"{self.package}.application.interfaces.dto", "dto")
        head = "\n".join([HEADER.format(source=self.path.relative_to(self.root)), "", imports_block(self.imports)])
        return "\n\n".join([head, *blocks]) + "\n"

    def signature(self, method: str, definition: MethodSpec, where: str) -> str:
        arguments = "".join(f", {name}: {self.reference(text, where)}" for name, text in definition.args.items())
        return f"async def {method}(self{arguments}) -> {self.reference(definition.returns, where)}"

    def interface_code(self, name: str, interface: InterfaceSpec) -> str:
        if not name.startswith("I"):
            raise self.fail(f"{name}: a port name starts with I")
        self.add_import(f"{self.package}.application.interfaces.port", "IPort")
        lines = [f"class {name}(IPort):", *docstring(interface.doc, "    ")]
        if interface.scope != "request":
            lines += [f'    scope = "{interface.scope}"', ""]
        if not interface.methods and not interface.doc:
            lines.append("    pass")
        for method, definition in interface.methods.items():
            self.add_import("abc", "abstractmethod")
            signature = self.signature(method, definition, f"{name}.{method}")
            if definition.doc:
                lines += ["    @abstractmethod", f"    {signature}:", *docstring(definition.doc, "        ")]
            else:
                lines += ["    @abstractmethod", f"    {signature}: ...", ""]
        return "\n".join(lines).rstrip()

    def render_interfaces(self) -> str:
        self.imports = {}
        blocks = [self.interface_code(name, interface) for name, interface in self.spec.interfaces.items()]
        head = "\n".join([HEADER.format(source=self.path.relative_to(self.root)), "", imports_block(self.imports)])
        return "\n\n".join([head, *blocks]) + "\n"

    def use_case_code(self, use_case: str, definition: UseCaseDefinition) -> str:
        input_name = self.reference(self.input_name(use_case), use_case)
        output = self.reference(definition.output, f"{use_case}: output")
        ports = [
            f"    {field}: {self.reference(port, f'{use_case}.{field}')}" for field, port in definition.ports.items()
        ]
        return "\n".join(
            [
                "@use_case",
                f"class {use_case}(IUseCase[{input_name}, {output}]):",
                *ports,
                *([""] if ports else []),
                f"    async def __call__(self, data: {input_name}) -> {output}:",
                "        raise NotImplementedError",
            ]
        )

    def render_use_cases(self, written: set[str]) -> Skeleton | None:
        self.imports = {}
        blocks = [
            self.use_case_code(name, definition)
            for name, definition in self.spec.use_cases.items()
            if name not in written
        ]
        if not blocks:
            return None
        self.add_import(f"{self.package}.application.interfaces.use_case", "IUseCase")
        self.add_import(f"{self.package}.application.interfaces.use_case", "use_case")
        return Skeleton(imports_block(self.imports), "\n\n".join(blocks))

    def subclass_code(self, name: str, subclass: str, interface: InterfaceSpec) -> str:
        self.add_import(f"{self.package}.application.interfaces.{self.module}", name)
        lines = [f"class {subclass}({name}):"]
        if not interface.methods:
            lines.append("    pass")
        for method, definition in interface.methods.items():
            signature = self.signature(method, definition, f"{name}.{method}")
            lines += [f"    {signature}:", "        raise NotImplementedError", ""]
        return "\n".join(lines).rstrip()

    def render_subclasses(self, subclasses: dict[str, str], written: set[str]) -> Skeleton | None:
        self.imports = {}
        blocks = [
            self.subclass_code(name, subclass, self.spec.interfaces[name])
            for name, subclass in subclasses.items()
            if subclass not in written
        ]
        if not blocks:
            return None
        return Skeleton(imports_block(self.imports), "\n\n".join(blocks))

    def render_implementations(self, written: set[str]) -> Skeleton | None:
        return self.render_subclasses(
            {name: interface.implementation for name, interface in self.spec.interfaces.items()}, written
        )

    def render_fakes(self, written: set[str]) -> Skeleton | None:
        """Fakes for application tests: IItemRepository -> FakeItemRepository."""
        return self.render_subclasses({name: f"Fake{name.removeprefix('I')}" for name in self.spec.interfaces}, written)
