"""Render application DTOs, ports and one-time skeletons from the YAML specification."""

from pathlib import Path
from typing import NamedTuple

from tools.codegen.spec import ApplicationSpec, InterfaceSpec, MethodSpec, SpecError, UseCaseDefinition, import_object
from tools.codegen.types import SCALARS, SpecType, annotation, imports, parse_type

HEADER = "# Generated by tools.codegen from {source}. Do not edit."
SUFFIX = "UseCase"


class Skeleton(NamedTuple):
    """A skeleton to write or to append to what a human already wrote."""

    imports: str
    code: str


def imports_block(grouped: dict[str, set[str]]) -> str:
    return "\n".join(f"from {module} import {', '.join(sorted(names))}" for module, names in sorted(grouped.items()))


class ApplicationRenderer:
    """Renders DTOs, ports and skeletons from one application specification."""

    def __init__(self, package: str, path: Path, spec: ApplicationSpec, root: Path) -> None:
        self.package = package
        self.path = path
        self.spec = spec
        self.root = root
        self.module = path.stem
        self.imports: dict[str, set[str]] = {}

    def fail(self, message: str) -> SpecError:
        return SpecError(self.path, message)

    def add_import(self, module: str, name: str) -> None:
        self.imports.setdefault(module, set()).add(name)

    def spec_type(self, text: str, where: str) -> SpecType:
        spec_type = parse_type(text)
        if not spec_type.is_scalar and spec_type.name not in self.spec.dtos:
            known = ", ".join([*SCALARS, *self.spec.dtos])
            raise self.fail(f"{where}: unknown type {text!r}, expected one of {known}")
        for module, symbol in imports(spec_type):
            self.add_import(module, symbol)
        return spec_type

    def input_name(self, use_case: str) -> str:
        if not use_case.endswith(SUFFIX):
            raise self.fail(f"{use_case}: a use case name must end with {SUFFIX}")
        return f"{use_case.removesuffix(SUFFIX)}Input"

    def dto_names(self) -> set[str]:
        return set(self.spec.dtos) | {self.input_name(use_case) for use_case in self.spec.use_cases}

    def reference(self, text: str, where: str) -> str:
        """Resolve a type used outside the DTO module: a scalar, a DTO of this file or a dotted path."""
        spec_type = parse_type(text)
        if spec_type.name == "none":
            if spec_type.many or spec_type.optional:
                raise self.fail(f"{where}: none has no list or optional form")
            return "None"
        if spec_type.is_scalar:
            for module, symbol in imports(spec_type):
                self.add_import(module, symbol)
            return annotation(spec_type)
        if "." in spec_type.name:
            value = import_object(self.path, f"{self.package}.{spec_type.name}")
            self.add_import(value.__module__, value.__name__)
            return annotation(SpecType(value.__name__, spec_type.many, spec_type.optional))
        if spec_type.name not in self.dto_names():
            known = ", ".join([*SCALARS, *sorted(self.dto_names())])
            raise self.fail(f"{where}: unknown type {text!r}, expected one of {known} or a dotted path")
        self.add_import(f"{self.package}.application.dto.{self.module}", spec_type.name)
        return annotation(spec_type)

    def dto_code(self, name: str, fields: dict[str, str]) -> str:
        lines = ["@dto", f"class {name}:"]
        if not fields:
            lines.append("    pass")
        lines += [
            f"    {field}: {annotation(self.spec_type(text, f'{name}.{field}'))}" for field, text in fields.items()
        ]
        return "\n".join(lines)

    def check_output(self, use_case: str, definition: UseCaseDefinition) -> None:
        """A use case takes and returns DTOs: the dto-decorator check rejects anything else."""
        name = parse_type(definition.output).name
        if name != "none" and name not in self.dto_names():
            raise self.fail(f"{use_case}: output must be none or a DTO of this file, got {definition.output!r}")

    def render_dtos(self) -> str:
        self.imports = {}
        blocks = [self.dto_code(name, fields) for name, fields in self.spec.dtos.items()]
        for use_case, definition in self.spec.use_cases.items():
            self.check_output(use_case, definition)
            blocks.append(self.dto_code(self.input_name(use_case), definition.input))
        self.add_import(f"{self.package}.application.interfaces.dto", "dto")
        head = "\n".join([HEADER.format(source=self.path.relative_to(self.root)), "", imports_block(self.imports)])
        return "\n\n".join([head, *blocks]) + "\n"

    def signature(self, method: str, definition: MethodSpec, where: str) -> str:
        arguments = "".join(f", {name}: {self.reference(text, where)}" for name, text in definition.args.items())
        return f"async def {method}(self{arguments}) -> {self.reference(definition.returns, where)}"

    def interface_code(self, name: str, interface: InterfaceSpec) -> str:
        if not name.startswith("I"):
            raise self.fail(f"{name}: a port name starts with I")
        self.add_import(f"{self.package}.application.interfaces.port", "IPort")
        lines = [f"class {name}(IPort):"]
        if interface.scope != "request":
            lines += [f'    scope = "{interface.scope}"', ""]
        if not interface.methods:
            lines.append("    pass")
        for method, definition in interface.methods.items():
            self.add_import("abc", "abstractmethod")
            lines += ["    @abstractmethod", f"    {self.signature(method, definition, f'{name}.{method}')}: ...", ""]
        return "\n".join(lines).rstrip()

    def render_interfaces(self) -> str:
        self.imports = {}
        blocks = [self.interface_code(name, interface) for name, interface in self.spec.interfaces.items()]
        head = "\n".join([HEADER.format(source=self.path.relative_to(self.root)), "", imports_block(self.imports)])
        return "\n\n".join([head, *blocks]) + "\n"

    def use_case_code(self, use_case: str, definition: UseCaseDefinition) -> str:
        input_name = self.reference(self.input_name(use_case), use_case)
        output = self.reference(definition.output, f"{use_case}: output")
        return "\n".join(
            [
                "@use_case",
                f"class {use_case}(IUseCase[{input_name}, {output}]):",
                f"    async def __call__(self, _data: {input_name}) -> {output}:",
                "        raise NotImplementedError",
            ]
        )

    def render_use_cases(self, written: set[str]) -> Skeleton | None:
        self.imports = {}
        blocks = [
            self.use_case_code(name, definition)
            for name, definition in self.spec.use_cases.items()
            if name not in written
        ]
        if not blocks:
            return None
        self.add_import(f"{self.package}.application.interfaces.use_case", "IUseCase")
        self.add_import(f"{self.package}.application.interfaces.use_case", "use_case")
        return Skeleton(imports_block(self.imports), "\n\n".join(blocks))

    def implementation_code(self, name: str, interface: InterfaceSpec) -> str:
        self.add_import(f"{self.package}.application.interfaces.{self.module}", name)
        lines = [f"class {interface.implementation}({name}):"]
        if not interface.methods:
            lines.append("    pass")
        for method, definition in interface.methods.items():
            signature = self.signature(method, definition, f"{name}.{method}")
            lines += [f"    {signature}:", "        raise NotImplementedError", ""]
        return "\n".join(lines).rstrip()

    def render_implementations(self, written: set[str]) -> Skeleton | None:
        self.imports = {}
        blocks = [
            self.implementation_code(name, interface)
            for name, interface in self.spec.interfaces.items()
            if interface.implementation not in written
        ]
        if not blocks:
            return None
        return Skeleton(imports_block(self.imports), "\n\n".join(blocks))
