"""Render FastAPI routers and exception handlers from the YAML specification."""

import ast
import dataclasses
import json
import re
import subprocess
import sys
import tomllib
from collections.abc import Iterator
from contextlib import contextmanager
from enum import Enum
from functools import partial
from pathlib import Path
from types import ModuleType
from typing import Any, get_args, get_origin, get_type_hints

from tools.codegen.application import ApplicationRenderer, Skeleton
from tools.codegen.spec import (
    ApplicationSpec,
    EndpointSpec,
    FileSpec,
    Model,
    ResponseSpec,
    RouterSpec,
    SpecError,
    import_object,
    load_specs,
)
from tools.codegen.types import (
    SCALAR_BY_TYPE,
    SCALARS,
    SpecType,
    SpecTypeError,
    annotation,
    field_hint,
    imports,
    matches,
    parse_type,
    schema_matches,
    strip_optional,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
HEADER = "# Generated by tools.codegen from {source}. Do not edit."
SCHEMA_FILE = "spec.schema.json"
SCALAR_NAMES = tuple(SCALARS)
PATH_PARAM = re.compile(r"{(\w+)}")


class PackageNotFoundError(RuntimeError):
    def __init__(self, root: Path) -> None:
        super().__init__(f"{root / 'pyproject.toml'} names no root_package in [tool.importlinter]")


def find_package() -> str:
    """The layered package, as import-linter knows it: tests/ mirrors its layers, so a directory scan is ambiguous."""
    with (REPO_ROOT / "pyproject.toml").open("rb") as file:
        package = tomllib.load(file).get("tool", {}).get("importlinter", {}).get("root_package")
    if not isinstance(package, str):
        raise PackageNotFoundError(REPO_ROOT)
    return package


def spec_dir(package: str) -> Path:
    return REPO_ROOT / package / "presentation" / "fastapi" / "spec"


def generated_dir(package: str) -> Path:
    return REPO_ROOT / package / "presentation" / "fastapi" / "generated"


def application_spec_dir(package: str) -> Path:
    return REPO_ROOT / package / "application" / "spec"


def dto_dir(package: str) -> Path:
    return REPO_ROOT / package / "application" / "dto"


def interface_dir(package: str) -> Path:
    return REPO_ROOT / package / "application" / "interfaces"


def use_case_dir(package: str) -> Path:
    return REPO_ROOT / package / "application" / "use_cases"


def is_generated(path: Path) -> bool:
    return path.read_text(encoding="utf-8").startswith(HEADER.split("{", 1)[0])


def imports_block(grouped: dict[str, set[str]]) -> str:
    return "\n".join(f"from {module} import {', '.join(sorted(names))}" for module, names in sorted(grouped.items()))


def source_expression(source: str) -> str:
    kind, _, name = source.partition(".")
    return f"body.{name}" if kind == "body" else name


class Renderer:
    """Renders one router module from one specification file."""

    def __init__(self, package: str, path: Path, spec: RouterSpec, handlers: dict[str, int]) -> None:
        self.package = package
        self.path = path
        self.spec = spec
        self.handlers = handlers
        self.imports: dict[str, set[str]] = {}
        self.modules: dict[str, str] = {}
        self.enums: dict[str, type[Enum]] = {}
        self.derived: dict[str, str] = {}
        self.derived_from: dict[str, Any] = {}
        self.deriving: set[str] = set()

    def fail(self, message: str) -> SpecError:
        return SpecError(self.path, message)

    def add_import(self, module: str, name: str) -> None:
        self.imports.setdefault(module, set()).add(name)

    def add_type_imports(self, spec_type: SpecType) -> None:
        for module, symbol in imports(spec_type):
            self.add_import(module, symbol)

    def reference(self, cls: type) -> str:
        """Import the module of a class and return the name the generated code refers to the class by."""
        parts = cls.__module__.split(".")
        alias = parts[-1]
        if self.modules.setdefault(alias, cls.__module__) != cls.__module__:
            alias = "_".join(parts[-2:])
            if self.modules.setdefault(alias, cls.__module__) != cls.__module__:
                raise self.fail(f"{cls.__module__} cannot be imported as {alias}, rename one of the modules")
            self.add_import(".".join(parts[:-1]), f"{parts[-1]} as {alias}")
            return f"{alias}.{cls.__name__}"
        self.add_import(".".join(parts[:-1]), alias)
        return f"{alias}.{cls.__name__}"

    def dto(self, dotted: str) -> tuple[Any, str]:
        """Import a DTO and return it with the name the generated code refers to it by."""
        full = f"{self.package}.application.dto.{dotted}"
        value = import_object(self.path, full)
        if not (isinstance(value, type) and dataclasses.is_dataclass(value)):
            raise self.fail(f"{full} is not a DTO dataclass")
        return value, self.reference(value)

    def enum(self, cls: type[Enum]) -> str:
        name = self.reference(cls)
        self.enums[name] = cls
        return name

    def parse(self, text: str, where: str) -> SpecType:
        try:
            return parse_type(text)
        except SpecTypeError as error:
            raise self.fail(f"{where}: {error}") from error

    def spec_type(self, text: str, where: str) -> SpecType:
        """A type written in the specification: a scalar, a schema of this file or an enum like task.TaskStatus."""
        spec_type = self.parse(text, where)
        if "." in spec_type.name:
            value = self.dotted_enum(spec_type.name, where)
            self.enums[spec_type.name] = value
            return dataclasses.replace(spec_type, name=self.enum(value))
        if not spec_type.is_scalar and spec_type.name not in self.spec.schemas:
            known = ", ".join([*SCALAR_NAMES, *self.spec.schemas])
            raise self.fail(
                f"{where}: unknown type {text!r}, expected one of {known}, an enum like module.Name "
                "(optional: str?, list: list[str], default: int = 20)"
            )
        return spec_type

    def dotted_enum(self, dotted: str, where: str) -> type[Enum]:
        """An enum named by a dotted path: relative to application.dto, or to the package (domain.item.State)."""
        for prefix in (f"{self.package}.application.dto.", f"{self.package}."):
            try:
                value = import_object(self.path, f"{prefix}{dotted}")
            except SpecError:
                continue
            if isinstance(value, type) and issubclass(value, Enum):
                return value
            raise self.fail(f"{where}: {dotted} is not an enum")
        raise self.fail(f"{where}: cannot import {dotted}, relative to application.dto or to the package")

    def default(self, spec_type: SpecType) -> str | None:
        """The source of the default value of a field or parameter; None when it is required."""
        if spec_type.default is None:
            return "None" if spec_type.optional else None
        enum = self.enums.get(spec_type.name)
        if enum is None or spec_type.default == "None":
            return spec_type.default
        value = ast.literal_eval(spec_type.default)
        member = next((member for member in enum if member.value == value), None)
        if member is None:
            raise self.fail(f"{value!r} is not a value of {spec_type.name}")
        return f"{spec_type.name}.{member.name}"

    def derive(self, dto: Any, where: str) -> str:
        """Build a schema with the shape of a DTO. A schema declared by hand wins and is checked instead."""
        name: str = dto.__name__
        if name in self.spec.schemas:
            if not schema_matches(self.spec.schemas[name], dto, self.spec.schemas, self.enums):
                raise self.fail(f"{where}: schema {name} does not match {dto.__module__}.{name}")
            return name
        if name in self.derived:
            if self.derived_from[name] is not dto:
                raise self.fail(f"{where}: two DTOs are named {name}, declare the schema in schemas")
            return name
        if name in self.deriving:
            raise self.fail(f"{where}: {name} refers to itself, declare the schema in schemas")
        self.deriving.add(name)
        self.add_import("pydantic", "BaseModel")
        fields = dataclasses.fields(dto)
        hints = get_type_hints(dto)
        lines = [f"class {name}(BaseModel):"]
        lines += [f"    {field.name}: {self.field_type(hints[field.name], f'{name}.{field.name}')}" for field in fields]
        if not fields:
            lines.append("    pass")
        self.deriving.discard(name)
        self.derived[name] = "\n".join(lines)
        self.derived_from[name] = dto
        return name

    def field_type(self, hint: Any, where: str) -> str:
        inner, optional = strip_optional(hint)
        many = get_origin(inner) is list
        if many:
            (inner,) = get_args(inner) or (None,)
        name = SCALAR_BY_TYPE.get(inner)
        if name is None and isinstance(inner, type) and issubclass(inner, Enum):
            name = self.enum(inner)
        if name is None:
            if not dataclasses.is_dataclass(inner):
                raise self.fail(f"{where}: cannot describe {inner} as a schema field")
            name = self.derive(inner, where)
        spec_type = SpecType(name=name, many=many, optional=optional)
        self.add_type_imports(spec_type)
        return annotation(spec_type)

    def path_params(self, name: str, endpoint: EndpointSpec) -> dict[str, str | None]:
        found = PATH_PARAM.findall(f"{self.spec.prefix}{endpoint.path}")
        unknown = set(endpoint.request.path) - set(found)
        if unknown:
            raise self.fail(f"{name}: path.{', path.'.join(sorted(unknown))} is not in the URL")
        return {param: endpoint.request.path.get(param) for param in found}

    def declared(self, name: str, endpoint: EndpointSpec) -> dict[str, dict[str, str | None]]:
        return {
            "path": self.path_params(name, endpoint),
            "query": endpoint.request.query,
            "header": endpoint.request.header,
        }

    def body_fields(self, name: str, endpoint: EndpointSpec) -> dict[str, str]:
        if endpoint.request.body is None:
            return {}
        fields = self.spec.schemas.get(endpoint.request.body)
        if fields is None:
            raise self.fail(f"{name}: unknown schema {endpoint.request.body}")
        return fields

    def input_mapping(self, name: str, endpoint: EndpointSpec, input_dto: Any) -> dict[str, str]:
        """Map every Input field to a request source: by name, unless input says otherwise."""
        fields = [field.name for field in dataclasses.fields(input_dto)]
        unknown = set(endpoint.input) - set(fields)
        if unknown:
            raise self.fail(f"{name}: input maps {', '.join(sorted(unknown))}, not a field of {input_dto.__name__}")
        available: dict[str, list[str]] = {}
        for field in self.body_fields(name, endpoint):
            available.setdefault(field, []).append(f"body.{field}")
        for kind, params in self.declared(name, endpoint).items():
            for param in params:
                available.setdefault(param, []).append(f"{kind}.{param}")
        mapping = {}
        for field in fields:
            mapping[field] = endpoint.input.get(field) or self.only_source(name, input_dto, field, available)
        return mapping

    def only_source(self, name: str, input_dto: Any, field: str, available: dict[str, list[str]]) -> str:
        sources = available.get(field, [])
        if not sources:
            raise self.fail(
                f"{name}: nothing provides {input_dto.__name__}.{field}, add it to request or map it in input"
            )
        if len(sources) > 1:
            raise self.fail(f"{name}: {', '.join(sources)} all provide {field}, choose one in input")
        return sources[0]

    def parameter_types(
        self,
        name: str,
        endpoint: EndpointSpec,
        input_dto: Any,
        mapping: dict[str, str],
    ) -> dict[str, SpecType]:
        """Type every path, query and header parameter: as declared, or after the Input field it feeds."""
        fed = {source: field for field, source in mapping.items()}
        types: dict[str, SpecType] = {}
        for kind, params in self.declared(name, endpoint).items():
            for param, text in params.items():
                source = f"{kind}.{param}"
                declared = self.parse(text, f"{name}: {source}") if text is not None else None
                if declared is not None and declared.name:
                    spec_type = self.spec_type(str(text), f"{name}: {source}")
                else:
                    field = fed.get(source)
                    if field is None:
                        raise self.fail(f"{name}: {source} feeds no Input field, declare its type or remove it")
                    spec_type = self.parameter_type(field_hint(input_dto, field), f"{name}: {source}")
                    if declared is not None:
                        spec_type = dataclasses.replace(spec_type, default=declared.default)
                if kind == "path" and self.default(spec_type) is not None:
                    raise self.fail(f"{name}: {source} is a path parameter, it is always required")
                types[source] = spec_type
        return types

    def parameter_type(self, hint: Any, where: str) -> SpecType:
        inner, optional = strip_optional(hint)
        name = SCALAR_BY_TYPE.get(inner)
        if name is None and isinstance(inner, type) and issubclass(inner, Enum):
            name = self.enum(inner)
        if name is None:
            raise self.fail(f"{where}: only a scalar or an enum comes from a request parameter, got {inner}")
        return SpecType(name=name, optional=optional)

    def source_type(self, name: str, endpoint: EndpointSpec, source: str, types: dict[str, SpecType]) -> SpecType:
        kind, _, field = source.partition(".")
        if kind == "body":
            fields = self.body_fields(name, endpoint)
            if field not in fields:
                raise self.fail(f"{name}: {source}, no such field in {endpoint.request.body}")
            return self.spec_type(fields[field], f"{endpoint.request.body}.{field}")
        if source not in types:
            raise self.fail(f"{name}: {source}, no such request parameter")
        return types[source]

    def check_input(
        self,
        name: str,
        endpoint: EndpointSpec,
        input_dto: Any,
        mapping: dict[str, str],
        types: dict[str, SpecType],
    ) -> None:
        for field, source in mapping.items():
            spec_type = self.source_type(name, endpoint, source, types)
            if not matches(spec_type, field_hint(input_dto, field), self.spec.schemas, self.enums):
                raise self.fail(f"{name}: {source} does not match the type of {input_dto.__name__}.{field}")

    def argument(self, name: str, field: str, source: str, spec_type: SpecType, hint: Any) -> str:
        """The expression that fills an Input field: the wire value, or a schema turned into the DTO it feeds."""
        expression = source_expression(source)
        if spec_type.is_scalar or spec_type.name in self.enums:
            return expression
        inner, _ = strip_optional(hint)
        if spec_type.many:
            (inner,) = get_args(inner) or (None,)
        nested = self.flat_dto(name, field, inner)
        if spec_type.many:
            built = f"[{nested}(**item.model_dump()) for item in {expression}]"
        else:
            built = f"{nested}(**{expression}.model_dump())"
        return f"None if {expression} is None else {built}" if spec_type.optional else built

    def flat_dto(self, name: str, field: str, dto: Any) -> str:
        """A DTO built from a schema holds scalars only: the generator converts one level, not a tree."""
        hints = get_type_hints(dto)
        for nested in dataclasses.fields(dto):
            inner, _ = strip_optional(hints[nested.name])
            if get_origin(inner) is list:
                (inner,) = get_args(inner) or (None,)
            if inner not in SCALAR_BY_TYPE and not (isinstance(inner, type) and issubclass(inner, Enum)):
                raise self.fail(
                    f"{name}: {field} is filled from a schema, so {dto.__name__}.{nested.name} must be a scalar "
                    f"or an enum; a deeper tree is not converted"
                )
        return self.reference(dto)

    def check_file(self, name: str, file: FileSpec, output_dto: Any, output_many: bool) -> None:
        if output_dto is None or output_many:
            raise self.fail(f"{name}: a file response needs a single DTO as the use case output")
        if field_hint(output_dto, file.content) is not bytes:
            raise self.fail(f"{name}: {output_dto.__name__}.{file.content} must be bytes")
        if file.filename is not None and field_hint(output_dto, file.filename) is not str:
            raise self.fail(f"{name}: {output_dto.__name__}.{file.filename} must be str")

    def check_response(self, name: str, endpoint: EndpointSpec, output_dto: Any, output_many: bool) -> SpecType | None:
        if isinstance(endpoint.response, ResponseSpec):
            self.check_file(name, endpoint.response.file, output_dto, output_many)
            return None
        if output_dto is None:
            if endpoint.response is not None:
                raise self.fail(f"{name}: the use case returns nothing, remove response")
            return None
        if endpoint.response is None:
            return SpecType(name=self.derive(output_dto, name), many=output_many)
        spec_type = parse_type(endpoint.response)
        if spec_type.many != output_many:
            raise self.fail(f"{name}: response and the use case output disagree about being a list")
        fields = self.spec.schemas.get(spec_type.name)
        if fields is None:
            raise self.fail(f"{name}: unknown schema {spec_type.name}")
        if not schema_matches(fields, output_dto, self.spec.schemas, self.enums):
            raise self.fail(f"{name}: response {spec_type.name} does not match {output_dto.__name__}")
        return spec_type

    def schema_code(self, name: str, fields: dict[str, str]) -> str:
        self.add_import("pydantic", "BaseModel")
        lines = [f"class {name}(BaseModel):"]
        for field, text in fields.items():
            spec_type = self.spec_type(text, f"{name}.{field}")
            self.add_type_imports(spec_type)
            default = self.default(spec_type)
            lines.append(f"    {field}: {annotation(spec_type)}" + ("" if default is None else f" = {default}"))
        return "\n".join(lines)

    def parameters(self, endpoint: EndpointSpec, types: dict[str, SpecType]) -> tuple[list[str], list[str]]:
        required: list[str] = []
        optional: list[str] = []
        if endpoint.request.body:
            required.append(f"body: {endpoint.request.body}")
        for source, spec_type in types.items():
            kind, _, name = source.partition(".")
            self.add_type_imports(spec_type)
            declaration = f"{name}: {annotation(spec_type)}"
            if kind == "header":
                self.add_import("fastapi", "Header")
                self.add_import("typing", "Annotated")
                declaration = f"{name}: Annotated[{annotation(spec_type)}, Header()]"
            default = self.default(spec_type)
            if default is None:
                required.append(declaration)
            else:
                optional.append(f"{declaration} = {default}")
        return required, optional

    def error_responses(self, name: str, endpoint: EndpointSpec) -> dict[int, list[str]]:
        """Status -> names of the errors an endpoint declares; the statuses come from the errors sections."""
        statuses: dict[int, list[str]] = {}
        for dotted in endpoint.errors:
            error = import_object(self.path, f"{self.package}.{dotted}")
            status = self.handlers.get(f"{error.__module__}.{error.__name__}")
            if status is None:
                raise self.fail(f"{name}: {dotted} has no status, map it in the errors section of a router")
            statuses.setdefault(status, []).append(error.__name__)
        return statuses

    def route_options(self, name: str, endpoint: EndpointSpec, response: SpecType | None) -> list[str]:
        file = self.file_spec(endpoint)
        options = [f'"{endpoint.path}"']
        responses: dict[int, str] = {}
        if endpoint.status is not None:
            options.append(f"status_code={endpoint.status}")
        elif response is None and file is None:
            options.append("status_code=204")
        if file is not None:
            self.add_import("fastapi", "Response")
            options.append("response_class=Response")
            responses[endpoint.status or 200] = f'{{"content": {{"{file.media_type}": {{}}}}}}'
        for status, errors in self.error_responses(name, endpoint).items():
            self.add_import(f"{self.package}.presentation.fastapi.generated.errors", "ErrorResponse")
            responses[status] = f'{{"model": ErrorResponse, "description": "{", ".join(errors)}"}}'
        if responses:
            entries = ", ".join(f"{status}: {value}" for status, value in sorted(responses.items()))
            options.append(f"responses={{{entries}}}")
        if endpoint.summary:
            options.append(f'summary="{endpoint.summary}"')
        if endpoint.auth != "none":
            self.add_import("fastapi", "Security")
            self.add_import("fastapi.security", "HTTPBearer")
            auto_error = endpoint.auth == "required"
            options.append(f"dependencies=[Security(HTTPBearer(auto_error={auto_error}))]")
        return options

    def return_annotation(self, file: FileSpec | None, response: SpecType | None) -> str:
        if file is not None:
            return "Response"
        return "None" if response is None else annotation(response)

    def file_spec(self, endpoint: EndpointSpec) -> FileSpec | None:
        return endpoint.response.file if isinstance(endpoint.response, ResponseSpec) else None

    def file_body(self, file: FileSpec, call: str) -> list[str]:
        arguments = [f"content=output.{file.content}", f'media_type="{file.media_type}"']
        if file.filename is not None:
            disposition = f"f'attachment; filename=\"{{output.{file.filename}}}\"'"
            arguments.append(f'headers={{"content-disposition": {disposition}}}')
        return [f"    output = await {call}", f"    return Response({', '.join(arguments)})"]

    def endpoint_code(self, name: str, endpoint: EndpointSpec) -> str:
        input_dto, input_name = self.dto(endpoint.use_case.input)
        output_type = parse_type(endpoint.use_case.output)
        output_dto, output_name = (None, "None") if output_type.name == "none" else self.dto(output_type.name)
        mapping = self.input_mapping(name, endpoint, input_dto)
        types = self.parameter_types(name, endpoint, input_dto, mapping)
        self.check_input(name, endpoint, input_dto, mapping, types)
        response = self.check_response(name, endpoint, output_dto, output_type.many)

        self.add_import(f"{self.package}.application.interfaces.use_case", "IUseCase")
        self.add_import("dishka.integrations.fastapi", "FromDishka")
        self.add_import("dishka.integrations.fastapi", "inject")

        if output_type.many:
            output_name = f"list[{output_name}]"
        key = f"IUseCase[{input_name}, {output_name}]"
        arguments = [
            f"{field}={self.argument(name, field, source, self.source_type(name, endpoint, source, types), hint)}"
            for field, source in mapping.items()
            for hint in [field_hint(input_dto, field)]
        ]
        call = f"use_case({input_name}({', '.join(arguments)}))"

        file = self.file_spec(endpoint)
        if file is not None:
            body = self.file_body(file, call)
        elif response is None:
            body = [f"    await {call}"]
        elif response.many:
            body = [
                f"    output = await {call}",
                f"    return [{response.name}.model_validate(item, from_attributes=True) for item in output]",
            ]
        else:
            body = [
                f"    output = await {call}",
                f"    return {response.name}.model_validate(output, from_attributes=True)",
            ]

        required, optional = self.parameters(endpoint, types)
        parameters = [*required, f"use_case: FromDishka[{key}]", *optional]
        return "\n".join(
            [
                f"@router.{endpoint.method.lower()}({', '.join(self.route_options(name, endpoint, response))})",
                "@inject",
                f"async def {name}(",
                *(f"    {parameter}," for parameter in parameters),
                f") -> {self.return_annotation(file, response)}:",
                *body,
            ]
        )

    def render(self) -> str:
        schemas = [self.schema_code(name, fields) for name, fields in self.spec.schemas.items()]
        endpoints = [self.endpoint_code(name, endpoint) for name, endpoint in self.spec.endpoints.items()]
        self.add_import("fastapi", "APIRouter")
        tags = f", tags={self.spec.tags}" if self.spec.tags else ""
        header = HEADER.format(source=self.path.relative_to(REPO_ROOT))
        prologue = "\n".join(
            [header, "", imports_block(self.imports), "", f'router = APIRouter(prefix="{self.spec.prefix}"{tags})']
        )
        return "\n\n".join([prologue, *schemas, *self.derived.values(), *endpoints]) + "\n"


def error_handlers(package: str, specs: dict[Path, RouterSpec]) -> dict[str, int]:
    handlers: dict[str, int] = {}
    for path, spec in specs.items():
        for dotted, status in spec.errors.items():
            error = import_object(path, f"{package}.{dotted}")
            if not (isinstance(error, type) and issubclass(error, Exception)):
                raise SpecError(path, f"{dotted} is not an exception")
            key = f"{error.__module__}.{error.__name__}"
            if handlers.setdefault(key, status) != status:
                raise SpecError(path, f"{dotted} is already mapped to status {handlers[key]}")
    return handlers


def errors_module(package: str) -> str:
    """The body of an error response, shared by the handlers and the OpenAPI description of every router."""
    return "\n".join(
        [
            HEADER.format(source=spec_dir(package).relative_to(REPO_ROOT)),
            "",
            "from pydantic import BaseModel",
            "",
            "",
            "class ErrorResponse(BaseModel):",
            "    detail: str",
            "",
        ]
    )


def package_module(package: str, specs: dict[Path, RouterSpec], handlers: dict[str, int]) -> str:
    grouped: dict[str, set[str]] = {
        "collections.abc": {"Callable", "Coroutine"},
        "typing": {"Any"},
        "fastapi": {"APIRouter", "Request", "Response"},
        "fastapi.responses": {"JSONResponse"},
    }
    for dotted in handlers:
        module, _, name = dotted.rpartition(".")
        grouped.setdefault(module, set()).add(name)
    for path in sorted(specs):
        grouped[f"{package}.presentation.fastapi.generated.{path.stem}"] = {f"router as {path.stem}_router"}

    entries = [f"    {dotted.rpartition('.')[2]}: _respond({status})," for dotted, status in handlers.items()]
    routers = ", ".join(f"{path.stem}_router" for path in sorted(specs))
    return (
        "\n".join(
            [
                HEADER.format(source=spec_dir(package).relative_to(REPO_ROOT)),
                "",
                imports_block(grouped),
                "",
                "type Handler = Callable[[Request, Any], Coroutine[Any, Any, Response]]",
                "",
                "",
                "def _respond(status_code: int) -> Handler:",
                "    async def handler(_request: Request, error: Exception) -> Response:",
                '        return JSONResponse(status_code=status_code, content={"detail": str(error)})',
                "",
                "    return handler",
                "",
                "",
                f"routers: list[APIRouter] = [{routers}]",
                "",
                "exception_handlers: dict[int | type[Exception], Handler] = {",
                *entries,
                "}",
            ]
        )
        + "\n"
    )


def format_code(path: Path, text: str) -> str:
    name = str(path)
    fixed = run_ruff(["check", "--fix-only", "--silent", "--stdin-filename", name, "-"], text)
    return run_ruff(["format", "--stdin-filename", name, "-"], fixed)


def run_ruff(arguments: list[str], text: str) -> str:
    result = subprocess.run(  # noqa: S603
        [sys.executable, "-m", "ruff", *arguments],
        input=text,
        capture_output=True,
        text=True,
        check=True,
        cwd=REPO_ROOT,
    )
    return result.stdout


def application_renderers(package: str) -> dict[Path, ApplicationRenderer]:
    specs = load_specs(application_spec_dir(package), ApplicationSpec)
    return {path: ApplicationRenderer(package, path, spec, REPO_ROOT) for path, spec in specs.items()}


def application_files(package: str, renderers: dict[Path, ApplicationRenderer]) -> dict[Path, str]:
    files = {
        dto_dir(package) / f"{path.stem}.py": renderer.render_dtos()
        for path, renderer in renderers.items()
        if renderer.has_dtos()
    }
    files |= {
        interface_dir(package) / f"{path.stem}.py": renderer.render_interfaces()
        for path, renderer in renderers.items()
        if renderer.spec.interfaces
    }
    return {path: format_code(path, text) for path, text in files.items()}


@contextmanager
def installed(files: dict[Path, str]) -> Iterator[None]:
    """Import the freshly rendered application modules, so routers are checked against the specification.

    The modules they replace are put back on exit: code imported before keeps the classes of the package.
    """
    previous: dict[str, ModuleType | None] = {}
    try:
        for path, text in files.items():
            name = ".".join(path.relative_to(REPO_ROOT).with_suffix("").parts)
            previous[name] = sys.modules.get(name)
            module = ModuleType(name)
            module.__file__ = str(path)
            sys.modules[name] = module
            exec(compile(text, str(path), "exec"), module.__dict__)  # noqa: S102
        yield
    finally:
        for name, original in previous.items():
            if original is None:
                del sys.modules[name]
            else:
                sys.modules[name] = original


def generate() -> dict[Path, str]:
    package = find_package()
    files = application_files(package, application_renderers(package))
    specs = load_specs(spec_dir(package), RouterSpec)
    with installed(files):
        handlers = error_handlers(package, specs)
        routers = {
            generated_dir(package) / f"{path.stem}.py": Renderer(package, path, spec, handlers).render()
            for path, spec in specs.items()
        }
        routers[generated_dir(package) / "__init__.py"] = package_module(package, specs, handlers)
        routers[generated_dir(package) / "errors.py"] = errors_module(package)
    return files | {path: format_code(path, text) for path, text in routers.items()} | schema_files(package)


def parse_body(path: Path) -> list[ast.stmt]:
    if not path.is_file():
        return []
    try:
        return ast.parse(path.read_text(encoding="utf-8")).body
    except SyntaxError as error:
        raise SpecError(path, f"cannot be parsed: {error}") from error


def is_docstring(node: ast.stmt) -> bool:
    return isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant) and isinstance(node.value.value, str)


def extend(path: Path, body: list[ast.stmt], skeleton: Skeleton) -> str:
    """Put the new classes into what a human already wrote: imports on top, classes at the end."""
    if not body:
        return f"{skeleton.imports}\n\n{skeleton.code}\n"
    lines = path.read_text(encoding="utf-8").splitlines()
    at = (body[0].end_lineno or 0) if is_docstring(body[0]) else 0
    return "\n".join([*lines[:at], skeleton.imports, *lines[at:], "", skeleton.code]) + "\n"


def skeletons() -> dict[Path, str]:
    """Skeletons: the classes of the specification are added once, what is already written stays untouched."""
    package = find_package()
    files: dict[Path, str] = {}
    for path, renderer in application_renderers(package).items():
        targets = [
            (use_case_dir(package) / f"{path.stem}.py", renderer.render_use_cases),
            (REPO_ROOT / "tests" / "fakes" / f"{path.stem}.py", renderer.render_fakes),
        ]
        for module, subclasses in renderer.implementation_modules().items():
            target = (REPO_ROOT / package).joinpath(*module.split(".")).with_suffix(".py")
            targets.append((target, partial(renderer.render_subclasses, subclasses)))
        for target, render in targets:
            body = parse_body(target)
            skeleton = render({node.name for node in body if isinstance(node, ast.ClassDef)})
            if skeleton is not None:
                files[target] = extend(target, body, skeleton)
    return files


def schema_files(package: str) -> dict[Path, str]:
    """JSON Schema of the specifications, so an editor checks the YAML before the generator does."""
    models: dict[Path, type[Model]] = {
        application_spec_dir(package) / SCHEMA_FILE: ApplicationSpec,
        spec_dir(package) / SCHEMA_FILE: RouterSpec,
    }
    return {path: json.dumps(model.model_json_schema(), indent=2) + "\n" for path, model in models.items()}


def obsolete(package: str, files: dict[Path, str]) -> set[Path]:
    unknown = {path for path in generated_dir(package).glob("*.py") if path not in files}
    for directory in (dto_dir(package), interface_dir(package)):
        unknown |= {path for path in directory.glob("*.py") if path not in files and is_generated(path)}
    return unknown


def outdated(files: dict[Path, str]) -> list[Path]:
    package = find_package()
    changed = [path for path, text in files.items() if not path.is_file() or path.read_text(encoding="utf-8") != text]
    return sorted(obsolete(package, files) | set(changed))


def write(files: dict[Path, str]) -> list[Path]:
    package = find_package()
    generated_dir(package).mkdir(parents=True, exist_ok=True)
    changed = outdated(files)
    for path in obsolete(package, files):
        path.unlink()
    for path, text in files.items():
        path.write_text(text, encoding="utf-8")
    created = []
    for path, text in skeletons().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(format_code(path, text), encoding="utf-8")
        created.append(path)
    return sorted(changed + created)
